language: ruby
rvm:
  - 2.2.1
install:
  - cd ext/lose_kanone/
  - ruby extconf.rb
  - make
env:
  - RUBYLIB=ext
deploy:
  provider: rubygems
  api_key:
    secure: FhV6uOvDY3+4D8WR9M3Wi+CRvV1/pprrH36EOICzmPbnGW25No5maBcaQ3q/cCNB5x7AQnh2egCl0wJjGq2ny7xjYRgtLz9tTg9MoAoO+DUmghY/LHJot9UKRXp73LNy+6M0kpY0XUz+7C5dQxkIwW1SzM6AV2HelgH/F6GOrofp6KwqGNeA0qg5IXVZwuxXAAoX8XUtqGqde/ug1mzIXdVN2RGdR0TTDajYpTAHe7hykQdg9RbRvUJqGtw0TwKjvyX3d93YZ7uHmjzpWkQoHwG9r7cZsEx2B/IvO4cbLOBF+VKeIisyC7iePXy6Vj8YLxNqs2fuYJGjZpKp+0Ev5RYbN5mVq69POwtLhoCbxaRFcC1tiC0wQDNY+mAW3/qrP9Un1bzSOJcW/Dlk7YK/QLwGqS94ahf5k85pn59YbLpaDaqtzBfoUHaqwJKdh74Xxn64EtMrfsubm7fuCq/RzH0USj7hJymn4IQ4WhKi31hRzHs3dB42a0i7riXcUcP7iXkqCNQ91KkV3X/9ZgKOTdG4b3ZvkdTb8L+sQi4Xvg3xQU6vUG/jOzkcjzcxDJpNWihMSowGqPt+nE56P2s6GA9rwe6pTTgVuL0kHWiHylQYxAlhWevkp7OAdGBFS/Pnr0c8fSMKM6lr93ERTzr/BEKGlymEoAS6P+PUqoSj23U=
  gem: unsafe
  on:
    tags: true
    repo: bascht/unsafe
